### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by CityVibes** [EspressifApp/EsptouchForAndroid#11]
Null exception in library causing crash.
```
java.lang.NullPointerException
	at com.espressif.iot.esptouch.udp.UDPSocketServer.receiveSpecLenBytes(UDPSocketServer.java:113)
	at com.espressif.iot.esptouch.task.__EsptouchTask$1.run(__EsptouchTask.java:175)
```

**Comment by woshiwozwh** [comment]
@afunx 可以看一下这个问题吗？在新版本的sdk中解决了吗？我也是同样的问题

**Comment by afunx** [comment]
@woshiwozwh 我已经离开近一年了。
@EspressifApp 有时间的话，帮他看看。

**Comment by EspressifApp** [comment]
@woshiwozwh 请问这是用本项目编出的APK报的错还是你自己移植了esptouch相关代码或库在自己的程序中报的错误？

**Comment by HayTran** [comment]
I had the same the problem before, that is because you using already used port. You can fix that by using setReuseAddress() when constructor UDPServerSocket. Specifically, in **UDPSocketServer.java** line **55** , you replace the below code:

`this.mServerSocket = new DatagramSocket(port);`

by

```
this.mServerSocket = new DatagramSocket(null);
this.mServerSocket.setReuseAddress(true);
this.mServerSocket.bind(new InetSocketAddress(port));
```
Hope that may help you.
