### ISSUE TITLE
Crash app in the second starting ESPTouch

### ISSUE THREAD

**Issue by FisherKei** [EspressifApp/EsptouchForAndroid#14]
Why trying to restart ESPTouch, it fire a crash with log:

`E/AndroidRuntime: FATAL EXCEPTION: Thread-6 Process: com.***.***, PID: 15095 java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.DatagramSocket.receive(java.net.DatagramPacket)' on a null object reference at com.espressif.iot.esptouch.udp.UDPSocketServer.receiveSpecLenBytes(UDPSocketServer.java:113) at com.espressif.iot.esptouch.task`

Please help me

**Comment by HayTran** [comment]
I had the same the problem before, that is because you using already used port. You can fix that by using setReuseAddress() when constructor UDPServerSocket. Specifically, in UDPSocketServer.java line 55 , you replace the below code:

`this.mServerSocket = new DatagramSocket(port);`

by

```
this.mServerSocket = new DatagramSocket();
this.mServerSocket.setReuseAddress(true);
this.mServerSocket.bind(new InetSocketAddress(port));
```

Hope that may help you.

**Comment by FisherKei** [comment]
Wow it don't occur again, thank you very much @HayTran
